import pandas as pd
import numpy as np
import os
from openai import OpenAI
import json
import warnings
warnings.filterwarnings('ignore')

print("=" * 60)
print("SOCIAL MEDIA AI — OpenAI Insights Generator")
print("AI-powered campaign recommendations")
print("=" * 60)

# CHECK API KEY
api_key = os.environ.get('OPENAI_API_KEY')
if not api_key:
    print("❌ OPENAI_API_KEY not found!")
    print("   Run: $env:OPENAI_API_KEY='your-key-here'")
    exit()

client = OpenAI(api_key=api_key)
print("\n✅ OpenAI API connected!")

# LOAD DATA
df = pd.read_csv('data/global_ads_performance_dataset.csv')
df['date'] = pd.to_datetime(df['date'])
df = df.dropna()

# LOAD ANOMALIES IF EXISTS
anomaly_file = 'outputs/anomalies_detected.csv'
if os.path.exists(anomaly_file):
    anomalies = pd.read_csv(anomaly_file)
    print(f"✅ Loaded {len(anomalies)} flagged anomalies")
else:
    anomalies = df.sample(5)

# BUILD SUMMARY FOR AI
summary = {
    "total_campaigns": len(df),
    "platforms": df.groupby('platform')['ROAS'].mean().round(2).to_dict(),
    "industries": df.groupby('industry')['ROAS'].mean().round(2).to_dict(),
    "countries": df.groupby('country')['ROAS'].mean().round(2).to_dict(),
    "campaign_types": df.groupby('campaign_type')['ROAS'].mean().round(2).to_dict(),
    "overall_avg_roas": round(df['ROAS'].mean(), 2),
    "overall_avg_ctr": round(df['CTR'].mean(), 4),
    "overall_avg_cpc": round(df['CPC'].mean(), 2),
    "top_anomalies": anomalies[['platform','industry','country','ROAS','CTR','CPA']].head(5).to_dict('records')
}

print("\n📊 Data summary built — sending to GPT-4...")

# GENERATE INSIGHTS
def get_ai_insights(summary):
    prompt = f"""
You are a Senior Performance Marketing AI Analyst specializing in TikTok, Meta and Google Ads.

Analyze this real campaign performance data and provide actionable insights:

DATA SUMMARY:
{json.dumps(summary, indent=2)}

Please provide:
1. TOP 3 KEY FINDINGS from the data
2. PLATFORM RECOMMENDATIONS (which to invest more/less)
3. INDUSTRY OPPORTUNITIES (which verticals to prioritize)
4. ANOMALY ANALYSIS (what's wrong with flagged campaigns)
5. TOP 3 ACTIONABLE RECOMMENDATIONS to improve ROAS

Be specific, data-driven, and concise. Use the actual numbers from the data.
Format with clear sections and bullet points.
"""
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=1000,
        temperature=0.3
    )
    return response.choices[0].message.content

print("\n🤖 Generating AI insights...\n")
insights = get_ai_insights(summary)

print("=" * 60)
print("AI INSIGHTS — POWERED BY GPT-4o-mini")
print("=" * 60)
print(insights)

# SAVE INSIGHTS
os.makedirs('outputs', exist_ok=True)
with open('outputs/ai_insights.txt', 'w', encoding='utf-8') as f:
    f.write("SOCIAL MEDIA AI INSIGHTS\n")
    f.write("Generated by GPT-4o-mini\n")
    f.write("=" * 60 + "\n\n")
    f.write(insights)

print("\n\n💾 Insights saved → outputs/ai_insights.txt")

# GENERATE CAMPAIGN-SPECIFIC RECOMMENDATIONS
print("\n" + "=" * 60)
print("CAMPAIGN-SPECIFIC RECOMMENDATIONS")
print("=" * 60)

top_campaigns = df.nlargest(3, 'ROAS')[['platform','industry','country','ROAS','CTR','CPC','ad_spend']]
worst_campaigns = df.nsmallest(3, 'ROAS')[['platform','industry','country','ROAS','CTR','CPC','ad_spend']]

def get_campaign_recommendation(campaign, campaign_type):
    prompt = f"""
As a Performance Marketing AI, analyze this {campaign_type} campaign and give ONE specific actionable recommendation in 2-3 sentences:

Campaign: {campaign.to_dict()}

Be direct and specific. Start with the main action to take.
"""
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=150,
        temperature=0.3
    )
    return response.choices[0].message.content

print("\n🏆 TOP PERFORMING CAMPAIGNS:")
for _, camp in top_campaigns.iterrows():
    rec = get_campaign_recommendation(camp, "top performing")
    print(f"\n  {camp['platform']} | {camp['industry']} | {camp['country']} | ROAS: {camp['ROAS']:.2f}x")
    print(f"  💡 {rec.strip()}")

print("\n⚠️  UNDERPERFORMING CAMPAIGNS:")
for _, camp in worst_campaigns.iterrows():
    rec = get_campaign_recommendation(camp, "underperforming")
    print(f"\n  {camp['platform']} | {camp['industry']} | {camp['country']} | ROAS: {camp['ROAS']:.2f}x")
    print(f"  🔧 {rec.strip()}")

print("\n\n✅ AI Insights complete!")
print("🚀 Next: python streamlit_app.py — Live Dashboard!")
